version: "2"

networks:
  blankGenericTemplate:
    driver: bridge

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    container_name: nginx-proxy-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./tmp:/tmp
    networks:
      - blankGenericTemplate
    
  web:
    image: httpd:latest
    container_name: httpd-static-templates
    restart: always
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
    networks:
      - blankGenericTemplate